# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\".\n\nAddRequest\x12\x0f\n\x07value_1\x18\x01 \x02(\x05\x12\x0f\n\x07value_2\x18\x02 \x02(\x05\"\x1c\n\x08\x41\x64\x64Reply\x12\x10\n\x08response\x18\x01 \x02(\x03\x32-\n\nArithmetic\x12\x1f\n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\t.AddReply\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=16
  _globals['_ADDREQUEST']._serialized_end=62
  _globals['_ADDREPLY']._serialized_start=64
  _globals['_ADDREPLY']._serialized_end=92
  _globals['_ARITHMETIC']._serialized_start=94
  _globals['_ARITHMETIC']._serialized_end=139
# @@protoc_insertion_point(module_scope)
